build-Java:
	mkdir -p "$(ARTIFACTS_DIR)/java"
	curl -L https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz | \
		tar --strip-components=1 -C "$(ARTIFACTS_DIR)/java" -xzvf - jdk-15
